// react-app/src/nav-bar/NavBar.jsx
import React, { Component } from 'react';
import '../../../api-app/assets/css/nav-bar/nav-bar.component.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { NavLink } from 'react-router-dom';

class Navbar extends Component {
	
	constructor(props){
		
		super(props)
		
		/*this.state = {
			totalCantidadProductos: 0
		}*/
		
		this.OnLogOut = this.OnLogOut.bind(this);
	}
	
	componentDidMount() {
	  
  	}
	
	OnLogOut() {

		//Obtener datos almacenados Res
		let conexionSession = sessionStorage.getItem("ResConexion");

		//String to JSON la conexion a la sessión
		let conexionSessionJson = JSON.parse(conexionSession);

		//Convertir la conexion a false
		conexionSessionJson = { conexion: false };

		//Convertir JSON de LogOut a String
		let conexionLogOutString = JSON.stringify(conexionSessionJson);

		//Almacenar los datos LogOut
		sessionStorage.setItem("ResConexion", conexionLogOutString);

	}
	
	render(){
		
		return(
				<nav className="navbar navbar-expand-md navbar-light bg-light">
				  <a className="navbar-brand" href="">La Bodega</a>
				  <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span className="navbar-toggler-icon"></span>
				  </button>
				  <div className="collapse navbar-collapse justify-content-center justify-content-md-end" id="navbarNavAltMarkup">
					<div className="navbar-nav">
					  <NavLink exact to="/productos" activeClassName="active" className="nav-item nav-link text-center text-md-right"><FontAwesomeIcon icon="th" /></NavLink>
					  <NavLink exact to="/carrito" activeClassName="active" className="nav-item nav-link text-center text-md-right"><FontAwesomeIcon icon="shopping-cart" />
					  	<div id="infoCarrito">
					  		<p id="CantTxt"></p>
					  	</div>
					  </NavLink>
					  <a className="nav-item nav-link text-center text-md-right" href=""><FontAwesomeIcon icon="inbox" /></a>
					  <NavLink onClick={this.OnLogOut} exact to="/" activeClassName="active" className="nav-item nav-link text-center text-md-right"><FontAwesomeIcon icon="sign-out-alt" /></NavLink>
					</div>
				  </div>
				</nav>
			)
	}
	
}

export default Navbar;

// angular-app/src/app/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { faTh } from '@fortawesome/free-solid-svg-icons';
import { faShoppingCart } from '@fortawesome/free-solid-svg-icons';
import { faInbox } from '@fortawesome/free-solid-svg-icons';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['../../../../api-app/assets/css/nav-bar/nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
	
  faTh = faTh;
  faShoppingCart = faShoppingCart;
  faInbox = faInbox;
  faSignOutAlt = faSignOutAlt;
  
  constructor( ) { }
	
  OnLogOut() {
	  
	  //Obtener datos almacenados Res
	  let conexionSession = sessionStorage.getItem("ResConexion");
	  
	  //String to JSON la conexion a la sessión
	  let conexionSessionJson = JSON.parse(conexionSession);
	  
	  //Convertir la conexion a false
	  conexionSessionJson = { conexion: false };
	  
	  //Convertir JSON de LogOut a String
	  let conexionLogOutString = JSON.stringify(conexionSessionJson);
	  
	  //Almacenar los datos LogOut
	  sessionStorage.setItem("ResConexion", conexionLogOutString);
	  
  }

  ngOnInit() {
  }

}


<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="">La Bodega</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center justify-content-md-end" id="navbarNavAltMarkup">
	<div class="navbar-nav">
	  <a class="nav-item nav-link text-center text-md-right" routerLink="/productos" routerLinkActive="active"><fa-icon [icon]="faTh"></fa-icon></a>
	  <a class="nav-item nav-link text-center text-md-right" routerLink="/carrito" routerLinkActive="active">
	  	<fa-icon [icon]="faShoppingCart"></fa-icon>
	  	<div id="infoCarrito">
			<p id="CantTxt"></p>
		</div>
	  </a>
	  <a class="nav-item nav-link text-center text-md-right" href=""><fa-icon [icon]="faInbox"></fa-icon></a>
	  <a class="nav-item nav-link text-center text-md-right" (click)="OnLogOut()" routerLink="/"><fa-icon [icon]="faSignOutAlt"></fa-icon></a>
	</div>
  </div>
</nav>
