// react-app/src/log-in/LogIn.jsx
import React, { Component } from 'react';
import '../../../api-app/assets/css/log-in/log-in.component.css';

import { Redirect } from 'react-router';


import logIn from '../ConexionApi/FetchLogInPromise';

class LogIn extends Component {
	
	constructor(props){
		
		super(props)
		
		this.state = {
			conexion: false
		}
		
		this.OnLogIn = this.OnLogIn.bind(this);
	}
	
	componentDidMount() {
		
	  //Obtener datos almacenados Res
	  let conexionSession = sessionStorage.getItem("ResConexion");
	  
	  if(conexionSession === null){
		  
		  this.setState({ conexion: false });
		  
	  } else {
		  
		  //String to JSON la conexion a la sessión
		  let conexionSessionJson = JSON.parse(conexionSession);
		  
		  //asignar valor de sessión a variable de conexión
		  this.setState({ conexion: conexionSessionJson.conexion });
		  
		  if(this.state.conexion === true){
			    return <Redirect to='/productos' />
				//console.log(this.state.conexion)
			}else {
				//console.log(this.usuario.conexion)
			}
		  
	  }
	  
  	}
	
	OnLogIn(event){
		
		event.preventDefault();
			
		let valpass = document.querySelector('#password').value
			
		let email = document.querySelector('#email').value

		let serializeinfo = `email=${email}&password=${valpass}`;
		  
		//console.log(valpass, email, serializeinfo)
			
		let url = "http://localhost/api/users";
			
		logIn(url, serializeinfo, this);
		
		if(this.state.conexion === false){
			document.querySelector('#error').style.display = "block";
		}
		
	}
	
	render(){
		//console.log(this.state.conexion);
		if (this.state.conexion === true) {
		  return <Redirect to='/productos' />
		} else {
			return(
				<div id="logIn-container" className="container-fluid">
					<div id="formContainer" className="row align-items-center">
						<div className="card card-outline-secondary col-12 col-sm-6 col-lg-4 mx-auto">
							<div className="card-header">
								<h3 className="text-center">Iniciar Sesión</h3>
							</div>
							<div className="card-body">
								<form className="form text-center" id="loginForm" onSubmit={this.OnLogIn} >
									<div className="form-group text-left">
										<label htmlFor="email">Correo Electrónico</label>
										<input type="email" className="form-control" name="email" id="email" defaultValue="" required />
									</div>
									<div className="form-group text-left">
										<label htmlFor="password">Contraseña</label>
										<input type="password" className="form-control" id="password" defaultValue="" required />
									</div>
									<div id="error" className="form-group text-left">
										<p className="text-danger text-left">Error en el inicio de sesión</p>
									</div>
									<button type="submit" className="btn btn-success btn-lg" id="btnLogin">Ingresar</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			);
		}
	}
}

export default LogIn;

// angular-app/src/app/log-in/log-in.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { FetchLogInPromiseService } from '../ConexionApi/fetch-log-in-promise.service';

@Component({
  selector: 'LogIn',
  templateUrl: './log-in.component.html',
  styleUrls: ['../../../../api-app/assets/css/log-in/log-in.component.css']
})
export class LogInComponent implements OnInit {
	
  public usuario: any = {
	  conexion: false
  }
	
  constructor( private logInService : FetchLogInPromiseService, private router:Router ) { }
	
  OnLogIn(event){
	  
	event.preventDefault();
	  
	let valpass = (<HTMLInputElement>document.querySelector('#password')).value
  
	let email = (<HTMLInputElement>document.querySelector('#email')).value
	
	this.logInService.logIn(email, valpass).subscribe(res => {
		
		//JSON to String Res
		let ResString = JSON.stringify(res);
		
		//Almacenar los datos Res
		sessionStorage.setItem("ResConexion", ResString);
		
		//Obtener datos almacenados Res
		let conexionSession = sessionStorage.getItem("ResConexion");
		
		//String to JSON la conexion a la sessión
		let conexionSessionJson = JSON.parse(conexionSession);
		
		//asignar valor de sessión a variable de conexión
		this.usuario = conexionSessionJson;
		
		if(this.usuario.conexion === true){
			this.router.navigate(['/productos'])
			//console.log(this.usuario.conexion)
		}else if(this.usuario.conexion === false){
			(<HTMLInputElement>document.querySelector('#error')).style.display = "block";
		}
	})  
  }

   ngOnInit() {
	    
	  //Obtener datos almacenados Res
	  let conexionSession = sessionStorage.getItem("ResConexion");
	  
	  if(conexionSession === null){
		  this.usuario.conexion = false
	  } else {
		  //String to JSON la conexion a la sessión
		  let conexionSessionJson = JSON.parse(conexionSession);
		  //asignar valor de sessión a variable de conexión
		  this.usuario = conexionSessionJson;
		  
		  if(this.usuario.conexion === true){
			this.router.navigate(['/productos'])
				//console.log(this.usuario.conexion)
			}else {
				//console.log(this.usuario.conexion)
			}
	  }
	   
  }

}

<div id="logIn-container" class="container-fluid">
	<div id="formContainer" class="row align-items-center">
        <div class="card card-outline-secondary col-12 col-sm-6 col-lg-4 mx-auto">
            <div class="card-header">
                <h3 class="text-center">Iniciar Sesión</h3>
            </div>
            <div class="card-body">
                <form class="form text-center" ngNativeValidate id="loginForm" (submit)="OnLogIn($event)">
                    <div class="form-group text-left">
                        <label for="email">Correo Electrónico</label>
                        <input type="email" class="form-control" name="email" id="email" required>
                    </div>
                    <div class="form-group text-left">
                        <label for="password">Contraseña</label>
                        <input type="password" class="form-control" id="password" required />
                    </div>
                    <div id="error" className="form-group text-left">
						<p class="text-danger text-left">Error en el inicio de sesión</p>
					</div>
                    <button type="submit" class="btn btn-success btn-lg" id="btnLogin">Ingresar</button>
                </form>
            </div>
        </div>
	</div>
</div>
