// react-app/src/carrito/Carrito.jsx
import React from 'react';
import '../../../api-app/assets/css/carrito/carrito.component.css';

import FetchPago from '../ConexionApi/FetchPagarPromise';

import { Redirect } from 'react-router';
import { NavLink } from 'react-router-dom';

import Navbar from '../nav-bar/NavBar.jsx';

let Carrito = props => {
	
	//Obtener datos almacenados Res
	let conexionSession = sessionStorage.getItem("ResConexion");

	//String to JSON la conexion a la sessión
	let conexionSessionJson = JSON.parse(conexionSession);
	
	let CancelarCarrito = () => {
		
		//Creando el Carrito
		let carrito = conexionSessionJson.carrito
		carrito = []
		
		//Vaciando Productos de ThisDataJson
		Object.assign(conexionSessionJson,
			{
				"carrito": carrito
			}
		);

		//JSON to String Carrito
		let carritoString = JSON.stringify(conexionSessionJson)

		//Almacenar los datos del carrito en Sessión
		sessionStorage.setItem("ResConexion", carritoString);

	}
	
	if(conexionSession === null || conexionSessionJson.conexion === false){
			  
		return <Redirect to='/' />

	} else if(conexionSessionJson.conexion === true) {
		
		//Creando el Carrito
		let carrito = conexionSessionJson.carrito
		
		//console.log(carrito)
		
		//Subtotal para sacar Total
		let subtotal = carrito.map((item)=>{
			return item.precio * item.productoCant
		})
		//console.log(subtotal);
		
		//Sacando el Total
		var total = 0;
		
		for (var i = 0; i < subtotal.length; i++) {
		  total += subtotal[i]
		}
		
		//console.log(carrito);
		
		let PagarCarrito = () => {
			let CarritoStr = JSON.stringify(carrito)
			let serializeinfo = `carrito=${CarritoStr}`;
			let url = "http://localhost/api/productos";
			FetchPago(url, serializeinfo, this);
			
			CancelarCarrito()
			
		}
		
		return(
			<div id="carritoContainer">
				<Navbar />
				<div id="carritoSubContainer" className="container-fluid">
					<div className="row">
						<div className="col-12 col-sm-6">
							<h1 className="text-left">Carrito de Compras</h1>
						</div>
					</div>
					<div className="row">
						<div id="carritoProductoContainer" className="col-12 col-sm-6">
							{
								carrito.map((item)=>{
									
									//sacando los subtotales
									let subtotal = item.precio * item.productoCant 

									return(
										<div className="row" key={item.id}>
											<div className="col-12 col-sm-6">
												<img className="img-responsive col-12" src={`http://localhost/${item.imgUrl}`} alt={item.imgUrl}/>
												<p className="col-12"><strong>Subtotal:</strong> Q.{subtotal}</p>
											</div>
											<div className="col-12 col-sm-6">
												<h5 className="col-12">{item.producto}</h5>
												<p className="col-12"><strong>Unidades:</strong> {item.productoCant}</p>
											</div>
										</div>
									)
								})

							}
						</div>
						<div className="col-12 col-sm-6">
							<h2>Total: Q.{total}</h2>
							<div className="btn-group" role="group" aria-label="Basic example">
							  <NavLink exact to="/productos" onClick={CancelarCarrito}><button id="botonCancelar" type="button" className="btn btn-light">Cancelar</button></NavLink>
							  <NavLink exact to="/productos" onClick={PagarCarrito}><button id="botonPagar" type="button" className="btn btn-light">Pagar</button></NavLink>
							</div>
						</div>
					</div>
				</div>
			</div>
		)

	}
}

export default Carrito;

// angular-app/src/app/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core';

import { NavBarComponent } from '../nav-bar/nav-bar.component';

import { Router } from '@angular/router';

import { FetchProductosPromiseService } from '../ConexionApi/fetch-productos-promise.service';

@Component({
  selector: 'app-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['../../../../api-app/assets/css/carrito/carrito.component.css']
})
export class CarritoComponent implements OnInit {
	
  public carrito: any[] = []
  
  public total: number
  
  public conexionSessionCarrito: any
  
  public conexionSessionCarritoJson: any

  constructor( private router:Router, private ProductosService : FetchProductosPromiseService ) { }
	
  CancelarCarrito = () => {
	  
	  	//Obtener datos almacenados Res
		let conexionSession = sessionStorage.getItem("ResConexion");

		//String to JSON la conexion a la sessión
		let conexionSessionJson = JSON.parse(conexionSession);
		
		//Creando el Carrito
		let carrito = conexionSessionJson.carrito
		carrito = []
		
		//Vaciando Productos de ThisDataJson
		Object.assign(conexionSessionJson,
			{
				"carrito": carrito
			}
		);

		//JSON to String Carrito
		let carritoString = JSON.stringify(conexionSessionJson)

		//Almacenar los datos del carrito en Sessión
		sessionStorage.setItem("ResConexion", carritoString);

  }
  
  PagarCarrito = () => {
	  
	  let carrito = this.carrito;
	  
	  this.ProductosService.Pagar(carrito).subscribe()
	  
	  this.CancelarCarrito()
	  
  }

  ngOnInit() {
	//Obtener datos almacenados Res
	let conexionSession = sessionStorage.getItem("ResConexion");

	//String to JSON la conexion a la sessión
	let conexionSessionJson = JSON.parse(conexionSession);
	
	if(conexionSession === null || conexionSessionJson.conexion === false){
			  
		this.router.navigate(['/'])

	} else if(conexionSessionJson.conexion === true) {
		
		//Creando el Carrito
		let carrito = conexionSessionJson.carrito
		
		//console.log(carrito)
		
		//Subtotal para sacar Total
		let subtotal = carrito.map((item)=>{
			return item.precio * item.productoCant
		})
		
		//console.log(subtotal);
		
		//Sacando el Total
		var total = 0;
		
		for (var i = 0; i < subtotal.length; i++) {
		  total += subtotal[i]
		}
		
		this.carrito = carrito
		
		this.total = total
		
		//console.log(total);

	}
  }

}

<div id="carritoContainer">
	<nav-bar></nav-bar>
	<div id="carritoSubContainer" class="container-fluid">
		<div class="row">
			<div class="col-12 col-sm-6">
				<h1 class="text-left">Carrito de Compras</h1>
			</div>
		</div>
		<div class="row">
			<div id="carritoProductoContainer" class="col-12 col-sm-6">
							<div *ngFor="let item of carrito" class="row">
								<div class="col-12 col-sm-6">
									<img class="img-responsive col-12" src="http://localhost/{{item.imgUrl}}" alt={{item.imgUrl}}/>
									<p class="col-12"><strong>Subtotal:</strong> Q. {{item.precio * item.productoCant}}</p>
								</div>
								<div class="col-12 col-sm-6">
									<h5 class="col-12">{{item.producto}}</h5>
									<p class="col-12"><strong>Unidades:</strong> {{item.productoCant}}</p>
								</div>
							</div>
			</div>
			<div class="col-12 col-sm-6">
				<h2>Total: Q.{{total}}</h2>
				<div class="btn-group" role="group" aria-label="Basic example">
				  <a routerLink="/productos" (click)="CancelarCarrito($event)"><button id="botonCancelar" type="button" class="btn btn-light">Cancelar</button></a>
				  <a routerLink="/productos" (click)="PagarCarrito($event)"><button id="botonPagar" type="button" class="btn btn-light">Pagar</button></a>
				</div>
			</div>
		</div>
	</div>
</div>
